### ISSUE TITLE
为什么现在不能使用了呢，觉得这个网站挺有用的？

### ISSUE THREAD

**Issue by quoniammm** [everyx/mathjax.everyx.in#3]
502 Bad Gateway

nginx/1.4.6 (Ubuntu)

**Comment by everyx** [comment]
你好，需要迁移服务器，一直比较懒，这个周末搞定吧，谢谢提醒，届时通知你 ：）

**Comment by everyx** [comment]
你好，已经迁移完成，不过目前没有缓存设计，生成方面还是比较慢的，见谅，有时间我在改进

**Comment by quoniammm** [comment]
赞～
