### ISSUE TITLE
报错 怎么解决 

### ISSUE THREAD

**Issue by yangjie21** [everyx/mathjax.everyx.in#4]
![image](https://user-images.githubusercontent.com/19204745/56104403-17ae9400-5f6a-11e9-8cf8-834eece5f043.png)

**Comment by everyx** [comment]
你好，这个项目已经停止维护了，请问你具体需求是什么呢？这个报错是因为依赖没有安装好，需要安装 https://github.com/mathjax/MathJax-node

**Comment by yangjie21** [comment]
你好 我现在是小程序那边 没有组件写 mathjax 想后端 golang 处理成图片  或着嵌入webview 实现  问一下 你们是怎么实现的

**Comment by everyx** [comment]
> 
> 
> 你好 我现在是小程序那边 没有组件写 mathjax 想后端 golang 处理成图片 或着嵌入webview 实现 问一下 你们是怎么实现的

看了一下 MathJax 项目，工具已经迁移到 https://github.com/mathjax/mathjax-node-cli/tree/master/bin 了，我是调用的这个工具直接生成图片的，如果你想直接用 go 渲染 MathJax 的，你可以需要再去想想其他办法了

**Comment by yangjie21** [comment]
好的 谢谢 现在 就是用的 bin
